name: ci
run-name: ${{github.actor}} verifying my code

on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"

jobs:
  check_linux_program_compilation:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@master
        with:
          repository: ""

      - name: Build project
        run: make

      - name: Check file
        run: |
          for file in ${{ vars.EXECUTABLES }};do
             if [ ! -x "./build/$file" ]; then
              echo"File $file does not exist or is not executable"
              exit 1
            fi
          done

  # run_tests:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 2
  #   container: epitechcontent/epitest-docker:latest
  #   needs:  check_program_compilation
  #   steps:

  #     - name: Checkout GH repository
  #       uses: actions/checkout@master
  #       with:
  #         repository: ''

  #     - name: Compile tests binaries
  #       run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    # needs:  run_tests
    needs: [check_linux_program_compilation]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: # <-- use 'secrets' to pass credential information.
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
