name: ci
run-name: ${{github.actor}} verifying my code

on:
  push:
    branches-ignore:
      - "ga-ignore-"
  pull_request:
    branches-ignore:
      - "ga-ignore-"

jobs:
  check_linux_program_compilation:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # container: epitechcontent/epitest-docker:latest
    env:
      EXECUTABLES: "pbrain-gomoku-ai"
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4

      - name: Build project
        run: make

      - name: Check executables
        run: |
          for file in $EXECUTABLES; do
            if [ ! -x "./$file" ]; then
              echo "File $file does not exist or is not executable"
              exit 1
            fi
          done

  # run_tests:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 2
  #   container: epitechcontent/epitest-docker:latest
  #   needs: check_linux_program_compilation
  #   steps:
  #     - name: Checkout GH repository
  #       uses: actions/checkout@v4

  #     - name: Compile test binaries
  #       run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [check_linux_program_compilation]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
